# configuration for master branch
-  branches:
    only:
      - master

    version: 5.5.0.{build}-beta
    image: Visual Studio 2017 Preview
    configuration: AppVeyor
    install:
    - cmd: 
    nuget:
    disable_publish_on_pr: true

    environment:
      # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: true


    build_script:
      # Add test when I can work out why the tests dont run on appveyor: dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build when I can 
    - cmd: >-
        dotnet build DynamicData.sln --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
        dotnet pack DynamicData\DynamicData.csproj --configuration Release --no-build --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION%
        appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
        appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.symbols.nupkg

    test: off

    deploy:
    - provider: NuGet
      api_key:
        secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
      skip_symbols: false
        # Only publish if the trigger was a Git tag
        # git tag v0.1.0-beta
        # git push origin --tags
        appveyor_repo_tag: true

# configuration for version 4 branch
-
  branches:
    only:
      - Version4

    version: 4.15.0.{build}-beta
    image: Visual Studio 2017 Preview
    configuration: AppVeyor
    install:
    - cmd: 
    nuget:
      disable_publish_on_pr: true

    environment:
      # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    build_script:
    - cmd: >-
        dotnet build DynamicData.sln --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
        dotnet pack DynamicData\DynamicData.csproj --configuration Release --no-build --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION%
        appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
        appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.symbols.nupkg
    
    test: off

    deploy:
    - provider: NuGet
      api_key:
        secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
      skip_symbols: false
        # Only publish if the trigger was a Git tag
        # git tag v0.1.0-beta
        # git push origin --tags
        appveyor_repo_tag: true
