# configuration for master
-
  branches:
    only:
      - master

  environment:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  version: 5.5.0.{build}-beta
  image: Visual Studio 2017 Preview
  configuration: Release
  install:
  - cmd: 
  nuget:
    disable_publish_on_pr: true

  # Hangs indefinitely! dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build
  build_script:
  - cmd: >-
      dotnet --info

      dotnet build DynamicData.sln --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack DynamicData\DynamicData.csproj --configuration Release --no-build --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION%
      
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
      
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.symbols.nupkg
  
  test_script:
-   cmd: dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build

  deploy:
  - provider: NuGet
    api_key:
      secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
    skip_symbols: false
    on:
      # Only publish from the master branch
      branch: master
      appveyor_repo_tag: true

# configuration for version 4
-
  branches:
    only:
      - Version4

  environment:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  version: 4.15.0.{build}-beta
  image: Visual Studio 2017 Preview
  configuration: Release
  install:
  - cmd: 
  nuget:
    disable_publish_on_pr: true

  # Hangs indefinitely! dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build
  build_script:
  - cmd: >-
      dotnet --info

      dotnet build DynamicData.sln --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack DynamicData\DynamicData.csproj --configuration Release --no-build --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION%
      
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.nupkg
      
      appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\DynamicData\bin\Release\DynamicData.%APPVEYOR_BUILD_VERSION%.symbols.nupkg
  
  test_script:
-   cmd: dotnet test DynamicData.Tests\DynamicData.Tests.csproj --configuration Release --no-build
  
  deploy:
  - provider: NuGet
    api_key:
      secure: CnOOhO/BwAogsD+dC9Q9BD38q6nxehHPS5LOHU977QtiJpqx3qE6vP+V+GHzpwac
    skip_symbols: false
    on:
      # Only publish from the Version4 branch
      branch: Version4
      appveyor_repo_tag: true
